### ISSUE TITLE
RuntimeError in L_metric function

### ISSUE THREAD

**Issue by zgpio** [gdjmck/AttentionBasedEmbeddingForMetricLearning#1]
```
Traceback (most recent call last):                                                                       
  File "train.py", line 228, in <module>                                                                 
    l_div, l_homo, l_heter = criterion.criterion(anchors, positives, negatives)                          
  File "/home/zgp/Project/ABE/criterion.py", line 48, in criterion                                       
    loss_heter = L_metric(anchors, negatives, False)                                                     
  File "/home/zgp/Project/ABE/criterion.py", line 9, in L_metric                                         
    d = torch.sum((feat1 - feat2).pow(2).view((-1, feat1.size(-1))), 1)                                  
RuntimeError: The size of tensor a (24) must match the size of tensor b (12) at non-singleton dimension 0
```
Please give some tips.

**Comment by flashjames** [comment]
I have the same problem. 

Do you have any idea why this happens @gdjmck ?

Or maybe you @zgpio , did you solve it?

**Comment by gdjmck** [comment]
> I have the same problem.
> 
> Do you have any idea why this happens @gdjmck ?
> 
> Or maybe you @zgpio , did you solve it?

Would you please print the size of `feat1` and `feat2` and see if they were the same shape?
Maybe I should add `Assertion` there to make sure everything's fine before computing the loss.

**Comment by gdjmck** [comment]
> ```
> Traceback (most recent call last):                                                                       
>   File "train.py", line 228, in <module>                                                                 
>     l_div, l_homo, l_heter = criterion.criterion(anchors, positives, negatives)                          
>   File "/home/zgp/Project/ABE/criterion.py", line 48, in criterion                                       
>     loss_heter = L_metric(anchors, negatives, False)                                                     
>   File "/home/zgp/Project/ABE/criterion.py", line 9, in L_metric                                         
>     d = torch.sum((feat1 - feat2).pow(2).view((-1, feat1.size(-1))), 1)                                  
> RuntimeError: The size of tensor a (24) must match the size of tensor b (12) at non-singleton dimension 0
> ```
> 
> Please give some tips.

Oh, sorry that I didn't see any notification. Any error pops up then?

**Comment by flashjames** [comment]
Nope no errors before.

I should have mentioned I used deepfashion1 inshop dataset, and your code is probably not tested on that.

I solved it by replacing the for-loop:
https://github.com/gdjmck/AttentionBasedEmbeddingForMetricLearning/blob/master/model.py#L169

With: 
https://github.com/suruoxi/DistanceWeightedSampling/blob/master/model.py#L151

Changes done, can be seen in my fork:
https://github.com/gdjmck/AttentionBasedEmbeddingForMetricLearning/compare/master...flashjames:master#diff-93ff136fae812392eb0f68d1ce89b7feR174

Didnt seem to change anything.

Anyways I didnt look into how much it changes stuff (but it was a small minor change), before I moved on to https://github.com/pierre-jacob/ICCV2019-Horde
Which had better results in the paper and on https://paperswithcode.com/task/metric-learning
and that code also was configured for INSHOP dataset.

I also had problems using the sampler (since there's thousands of classes in INSHOP dataset), so as an early try, I started with a RandomSampler.

The code is here in my fork: https://github.com/flashjames/AttentionBasedEmbeddingForMetricLearning

**Comment by flashjames** [comment]
If and only IF, you have time.

It would be nice to see code for the deefpashion INSHOP dataset.

By the way, thanks for your time and energy put into this project.

**Comment by gdjmck** [comment]
> If and only IF, you have time.
> 
> It would be nice to see code for the deefpashion INSHOP dataset.
> 
> By the way, thanks for your time and energy put into this project.

Sure, I'll try on this dataset :)
